### ISSUE TITLE
no function on buttons and deleting files impossible

### ISSUE THREAD

**Issue by maj0r1337** [stooged/ESP32-Server-900#1]
hi stooged,
if i click on goldhen nothing happens. can you tell me why?
the other problem is, i cant delete files in the file manager. 
greetings
maj0r

**Comment by stooged** [comment]
Make sure the esp32 library is up to date

https://github.com/espressif/arduino-esp32

**Comment by maj0r1337** [comment]
thx for the tip. ive installed this one https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
