### ISSUE TITLE
SPIFFS: mount failed

### ISSUE THREAD

**Issue by hamid0015** [stooged/ESP32-Server-900#3]
Hi,

I have a NodeMCU-32s. It has similar specs to WEMOS D32(4MB Flash, ESP32-WROOM-32)

I get no error on compiling and uploading the sketch, However;  It fails when I login to AP and try to upload bin files or change the config on 10.1.1.1/admin.html. Seems the Flash is read-only.

ESP32 library is up-to-date (2.0.2)

here the output on RST:

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:12776
load:0x40080400,len:3032
entry 0x400805e4
E (23) SPIFFS: mount failed, -10025

**Comment by stooged** [comment]
try this.

find this line of code in the setup function of the ESP32_Server_900.ino file
`
if (SPIFFS.begin()) {
`

change it to 
`
if (SPIFFS.begin(true)) {
`

reupload sketch and see if it works

**Comment by hamid0015** [comment]
Yeah it worked.
Thank you
